# Generated by Django 5.0.2 on 2024-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="cour_drive_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="other_drive_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="td_drive_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="tp_drive_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("Lesson", "cour"),
                    ("TD", "td"),
                    ("Exam", "exam"),
                    ("other", "other"),
                ],
                max_length=20,
            ),
        ),
    ]
