# Generated by Django 5.0.2 on 2024-03-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_module_cour_drive_id_module_other_drive_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="exam_drive_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("cour", "cour"),
                    ("td", "td"),
                    ("exam", "exam"),
                    ("other", "other"),
                    ("tp", "tp"),
                ],
                max_length=20,
            ),
        ),
    ]
